run:
  timeout: 3m
  tests: true
linters:
  enable:
    - govet
    - gosimple
    - staticcheck
    - revive
    - ineffassign
    - errcheck
    - gofmt
    - goimports
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

